### ISSUE TITLE
Can't compile using ghc 9.4

### ISSUE THREAD

**Issue by emberdart** [stepcut/plugins#20]
Hi,
I get the following compiling on 9.4.x:

```
       > [ 4 of 12] Compiling System.Plugins.Parser ( src/System/Plugins/Parser.hs, dist/build/System/Plugins/Parser.o, dist/build/System/Plugins/Parser.dyn_o )
       >
       > src/System/Plugins/Parser.hs:38:1: error:
       >     Ambiguous module name ‘Language.Haskell.Syntax’:
       >       it was found in multiple packages: ghc-9.4.2 haskell-src-1.0.4
       >    |
       > 38 | import Language.Haskell.Syntax
```

Unsure if one of these packages just reimports another, it may be possible to reduce dependencies now?

Thanks!

**Comment by emberdart** [comment]
Oooh, whoops - it's being worked on:

https://github.com/stepcut/plugins/pull/19

I'll use/work on that branch for now.
